### JSON Files

In [1]:
# Create a dictionary for each book with info such as author, genre, etc.
book1 = {'title': 'The Prophet',
         'author': 'Khalil Gibran',
         'genre': 'poetry',
         'tags': ['religion', 'spirituality', 'philosophy', 'Lebanon', 'Arabic', 'Middle East'],
         'book_id': '811.19',
         'copies': [{'edition_year': 1996,
                     'checkouts': 486,
                     'borrowed': False},
                    {'edition_year': 1996,
                     'checkouts': 443,
                     'borrowed': False}]
         }
         
book2 = {'title': 'The Little Prince',
         'author': 'Antoine de Saint-Exupery',
         'genre': 'children',
         'tags': ['fantasy', 'France', 'philosophy', 'illustrated', 'fable'],
         'id': '843.912',
         'copies': [{'edition_year': 1983,
                     'checkouts': 634,
                     'borrowed': True,
                     'due_date': '2017/02/02'},
                    {'edition_year': 2015,
                     'checkouts': 41,
                     'borrowed': False}]
         }

library = [book1, book2]
library

[{'title': 'The Prophet',
  'author': 'Khalil Gibran',
  'genre': 'poetry',
  'tags': ['religion',
   'spirituality',
   'philosophy',
   'Lebanon',
   'Arabic',
   'Middle East'],
  'book_id': '811.19',
  'copies': [{'edition_year': 1996, 'checkouts': 486, 'borrowed': False},
   {'edition_year': 1996, 'checkouts': 443, 'borrowed': False}]},
 {'title': 'The Little Prince',
  'author': 'Antoine de Saint-Exupery',
  'genre': 'children',
  'tags': ['fantasy', 'France', 'philosophy', 'illustrated', 'fable'],
  'id': '843.912',
  'copies': [{'edition_year': 1983,
    'checkouts': 634,
    'borrowed': True,
    'due_date': '2017/02/02'},
   {'edition_year': 2015, 'checkouts': 41, 'borrowed': False}]}]

In [2]:
import json
# Write the library of books to the file 'library.json'
with open('./library.json', 'w') as f:
    json.dump(library, f, indent=2)

In [5]:
# Read the json file
!cat ./library.json

[
  {
    "title": "The Prophet",
    "author": "Khalil Gibran",
    "genre": "poetry",
    "tags": [
      "religion",
      "spirituality",
      "philosophy",
      "Lebanon",
      "Arabic",
      "Middle East"
    ],
    "book_id": "811.19",
    "copies": [
      {
        "edition_year": 1996,
        "checkouts": 486,
        "borrowed": false
      },
      {
        "edition_year": 1996,
        "checkouts": 443,
        "borrowed": false
      }
    ]
  },
  {
    "title": "The Little Prince",
    "author": "Antoine de Saint-Exupery",
    "genre": "children",
    "tags": [
      "fantasy",
      "France",
      "philosophy",
      "illustrated",
      "fable"
    ],
    "id": "843.912",
    "copies": [
      {
        "edition_year": 1983,
        "checkouts": 634,
        "borrowed": true,
        "due_date": "2017/02/02"
      },
      {
        "edition_year": 2015,
        "checkouts": 41,
        "borrowed": false
      }
    ]
  }
]

In [6]:
# Read the json file using the json library
with open('./library.json', 'r') as f:
    reloaded_library = json.load(f)

reloaded_library

[{'title': 'The Prophet',
  'author': 'Khalil Gibran',
  'genre': 'poetry',
  'tags': ['religion',
   'spirituality',
   'philosophy',
   'Lebanon',
   'Arabic',
   'Middle East'],
  'book_id': '811.19',
  'copies': [{'edition_year': 1996, 'checkouts': 486, 'borrowed': False},
   {'edition_year': 1996, 'checkouts': 443, 'borrowed': False}]},
 {'title': 'The Little Prince',
  'author': 'Antoine de Saint-Exupery',
  'genre': 'children',
  'tags': ['fantasy', 'France', 'philosophy', 'illustrated', 'fable'],
  'id': '843.912',
  'copies': [{'edition_year': 1983,
    'checkouts': 634,
    'borrowed': True,
    'due_date': '2017/02/02'},
   {'edition_year': 2015, 'checkouts': 41, 'borrowed': False}]}]

In [7]:
# note that if we loaded it in without JSON
# the file would be interpreted as plain text

with open('./library.json', 'r') as f:
    library_string = f.read()

# this isn't what we want
library_string

'[\n  {\n    "title": "The Prophet",\n    "author": "Khalil Gibran",\n    "genre": "poetry",\n    "tags": [\n      "religion",\n      "spirituality",\n      "philosophy",\n      "Lebanon",\n      "Arabic",\n      "Middle East"\n    ],\n    "book_id": "811.19",\n    "copies": [\n      {\n        "edition_year": 1996,\n        "checkouts": 486,\n        "borrowed": false\n      },\n      {\n        "edition_year": 1996,\n        "checkouts": 443,\n        "borrowed": false\n      }\n    ]\n  },\n  {\n    "title": "The Little Prince",\n    "author": "Antoine de Saint-Exupery",\n    "genre": "children",\n    "tags": [\n      "fantasy",\n      "France",\n      "philosophy",\n      "illustrated",\n      "fable"\n    ],\n    "id": "843.912",\n    "copies": [\n      {\n        "edition_year": 1983,\n        "checkouts": 634,\n        "borrowed": true,\n        "due_date": "2017/02/02"\n      },\n      {\n        "edition_year": 2015,\n        "checkouts": 41,\n        "borrowed": false\n      }\n    ]\n  }\n]'

In [10]:
# Pandas can also read_json
# notice how it constructs the table
import pandas as pd
pd.read_json('./library.json')

,author,book_id,copies,genre,id,tags,title
0,Khalil Gibran,811.19,"[{'edition_year': 1996, 'checkouts': 486, 'bor...",poetry,NaN,"[religion, spirituality, philosophy, Lebanon, ...",The Prophet
1,Antoine de Saint-Exupery,NaN,"[{'edition_year': 1983, 'checkouts': 634, 'bor...",children,843.912,"[fantasy, France, philosophy, illustrated, fable]",The Little Prince

Panda's `read_json` method is capable of connecting directly to a URL (whether it's the address of a JSON file or an API connection) and reading the JSON without saving the file to our computer.

In [11]:
pd.read_json('https://api.github.com/repos/pydata/pandas/issues?per_page=5')

,assignee,assignees,author_association,body,closed_at,comments,comments_url,created_at,events_url,html_url,...,milestone,node_id,number,pull_request,repository_url,state,title,updated_at,url,user
0,NaN,[],NONE,I am trying out using pandas+sqlalchemy (speci...,NaT,2,https://api.github.com/repos/pandas-dev/pandas...,2019-10-27 01:44:31,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/29240,...,NaN,MDU6SXNzdWU1MTI5MDc1MDg=,29240,NaN,https://api.github.com/repos/pandas-dev/pandas,open,Trying to use to_sql on dataframe with numpy.n...,2019-10-27 06:04:42,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'kjfergu', 'id': 9022843, 'node_id':..."
1,NaN,[],CONTRIBUTOR,"Per discussion in #29165, this PR significantl...",NaT,0,https://api.github.com/repos/pandas-dev/pandas...,2019-10-26 21:06:21,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/29239,...,NaN,MDExOlB1bGxSZXF1ZXN0MzMyODAxNzE4,29239,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas,open,BENCH: Improve perf of rolling.Apply.time_rolling,2019-10-26 21:06:21,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'qwhelan', 'id': 440095, 'node_id': ..."
2,NaN,[],NONE,"closes #29227\r\n\r\nHi, it my first issues wi...",NaT,1,https://api.github.com/repos/pandas-dev/pandas...,2019-10-26 13:49:24,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/29237,...,NaN,MDExOlB1bGxSZXF1ZXN0MzMyNzY4NDMy,29237,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas,open,Replace _has_complex_internals #29227,2019-10-26 16:37:34,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'Aivengoe', 'id': 18753654, 'node_id..."
3,NaN,[],CONTRIBUTOR,[pandas/core/Indexes/timedeltas.py](https://gi...,NaT,0,https://api.github.com/repos/pandas-dev/pandas...,2019-10-26 12:47:00,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/29236,...,NaN,MDU6SXNzdWU1MTI4MzE2MTY=,29236,NaN,https://api.github.com/repos/pandas-dev/pandas,open,DOCS: Formatting Errors pandas.TimedeltaIndex,2019-10-26 12:55:42,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'HughKelley', 'id': 38143549, 'node_..."
4,NaN,[],NONE,"#### Code Sample, a copy-pastable example if p...",NaT,0,https://api.github.com/repos/pandas-dev/pandas...,2019-10-26 10:44:24,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/29235,...,NaN,MDU6SXNzdWU1MTI4MjA4NTA=,29235,NaN,https://api.github.com/repos/pandas-dev/pandas,open,Categories reordered to alphabetical when plot...,2019-10-26 16:27:39,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'dmey', 'id': 26348635, 'node_id': '..."

### Wikipedia Library

In [70]:
import wikipedia

# Extract info about Machine Learning
page = wikipedia.page("Machine_Learnin")
ML_df = pd.DataFrame({'topic': page.links})
ML_df.head(10)
# Data_Science_df.shape[0]

                                 topic
0  ACM Computing Classification System
1                ACM Computing Surveys
2                              ADALINE
3                            AT&T Labs
4                     Action selection
5   Active learning (machine learning)
6                     Adaptive website
7                  Affective computing
8                          Alan Turing
9                            Algorithm

### Beautiful Soup to Scrape Wikipedia Site

In [68]:
# Use BeautifulSoup library to extract the list of works by Vincent Van Gogh for example
from bs4 import BeautifulSoup
import requests
url = requests.get("http://en.wikipedia.org/wiki/List_of_works_by_Vincent_van_Gogh").text
soup = BeautifulSoup(url, 'lxml')
table = soup.find('table', class_="wikitable sortable")
# table
links = table.findAll('a')
# links

# List of works
works = []
for link in links:
    works.append(link.get('title'))
# Remove the None values
Van_Gogh_Works = []
for work in works:
    if work != None:
        Van_Gogh_Works.append(work)

# Unique values using the set function
Van_Gogh_Works = list(set(Van_Gogh_Works))
# Create a data frame
Van_Gogh_Works_df = pd.DataFrame({'Work': Van_Gogh_Works})
# len(Van_Gogh_Works)

# Extract the first few rows of the dataframe
Van_Gogh_Works_df.head()

                                                Work
0                     Green Wheat Field with Cypress
1                         Asnières (Van Gogh series)
2                               Worcester Art Museum
3  Paul Gauguin (Man in a Red Beret) (page does n...
4                                          Lying Cow